# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wp2mqTX3d72PYWKKQ5pEaqUwvI0MpPMX
"""

def isPalindrome(text):

    reversedText = ''

    for char in text:

        reversedText = char + reversedText



    if text == reversedText:

        return True

    else:

        return False
print(isPalindrome('level'))  # Вывод: True

print(isPalindrome('hello'))  # Вывод: False

print(isPalindrome('racecar'))  # Вывод: True

def register(name, surname, patronymic, age):

    registration_string = f"{surname} {name} {patronymic} {age} г.р. зарегистрирован"

    return registration_string
result = register("Иван", "Иванов", "Иванович", 1973)

print(result)

def maximum(a, b, c=None):

    if c is not None:

        if a > b and a > c:

            return a

        elif b > a and b > c:

            return b

        else:

            return c

    else:

        if a > b:

            return a

        else:

            return b
print(maximum(5, 10))         # Вывод: 10

print(maximum(5, 10, 8))      # Вывод: 10

print(maximum(10, 5, 8))      # Вывод: 10

print(maximum(10, 10, 8))     # Вывод: 10

print(maximum(8, 10, 10))     # Вывод: 10

print(maximum(10, 10, 10))    # Вывод: 10